<?php

/**
 * Implements hook_menu().
 */
function axelerant_menu() {
  $items['node/%node/json'] = array(
    'page callback' => '_axelerant_endpoint_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  return $items;
 }
 
 /**
 * Implements hook_form_alter() to add the "Site API key" text field on site information form.
 */
function axelerant_form_system_site_information_settings_alter(&$form, &$form_state) {
  $form['site_information']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API key'),
    '#default_value' => variable_get('siteapikey', 'No API Key yet'),
    '#required' => TRUE
  );
  $form['actions']['submit']['#value'] = t('Update Configuration');//update the text value of save button
  $form['#submit'][] = '_axelerant_form_system_site_information_settings_submit';
}

/**
 * Implements axelerant_endpoint_callback() to return the json object.
 */
function _axelerant_form_system_site_information_settings_submit(&$form, &$form_state){
  drupal_get_messages('status');
  drupal_set_message(t('Site API Key has been saved with '.variable_get('siteapikey', '').'.'), 'status', $repeat = TRUE);
}

 /**
 * Implements axelerant_endpoint_callback() to return the json object.
 */
function _axelerant_endpoint_callback($node) {
   $site_api_key = variable_get('siteapikey', '');
	if($node->type=='page' && !empty($site_api_key)){
		drupal_json_output($node);
	}else{
		drupal_access_denied();
	}
}